apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fossology.fullname" . }}-db
  labels:
    app.kubernetes.io/name: {{ include "fossology.fullname" . }}-db
{{ include "fossology.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "fossology.fullname" . }}-db
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "fossology.fullname" . }}-db
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}-scheduler
          image: "{{ .Values.dbimage.repository }}:{{ .Values.dbimage.tag }}"
          imagePullPolicy: {{ .Values.dbimage.pullPolicy }}
          env:
            - name: POSTGRES_DB
              value: {{ .Values.fossology.db_name }}
            - name: POSTGRES_USER
              value: {{ .Values.fossology.db_user }}
            - name: POSTGRES_PASSWORD
              value: {{ .Values.fossology.db_passord }}
            - name: POSTGRES_INITDB_ARGS
              value: '-E SQL_ASCII'
          ports:
            - name: postgrsql
              containerPort: {{ .Values.fossology.db_port}}
           
