{{- if (not .Values.fossology.externalSecret)  }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "fossology.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "fossology.fullname" . }}
{{ include "fossology.labels" . | indent 4 }}
type: Opaque
data:
  {{- if .Values.fossology.db_password }}
  db_password: {{ default "" .Values.fossology.db_password | b64enc | quote }}
  {{- else }}
  db_password: {{ randAlphaNum 10 | b64enc | quote }}
  {{- end }}
  {{- if .Values.fossology.db_user }}
  db_user: {{ .Values.fossology.db_user | b64enc | quote }}
  {{- end }}
  {{- if .Values.fossology.db_name }}
  db_name: {{ .Values.fossology.db_name | b64enc | quote }}
  {{- end }}
  {{- if .Values.fossology.db_host }}
  db_host: {{ .Values.fossology.db_host | b64enc | quote }}
  {{- else }}
  db_host: {{ include "fossology.dbname" . | b64enc | quote  }}
  {{- end }}
{{- end -}}