apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fossology.fullname" . }}-web
  labels:
    app.kubernetes.io/name: {{ include "fossology.fullname" . }}-web
{{ include "fossology.labels" . | indent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name:  {{ include "fossology.fullname" . }}-web
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name:  {{ include "fossology.fullname" . }}-web
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: web
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: FOSSOLOGY_DB_HOST
              value: {{ include "fossology.fullname" . }}-db
            - name: FOSSOLOGY_DB_NAME
              value: {{ .Values.fossology.db_name }}
            - name: FOSSOLOGY_DB_USER
              value: {{ .Values.fossology.db_user }}
            - name: FOSSOLOGY_DB_PASSWORD
              value: {{ .Values.fossology.db_passord }}
            - name: FOSSOLOGY_SCHEDULER_HOST
              value: localhost:8080
          ports:
            - name: http
              containerPort: 80
              hostPort: 8081
              protocol: TCP
          command:
             - "/fossology/docker-entrypoint.sh"
             - "web"
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          volumeMounts:
            - mountPath: /srv/fossology/repository/
              name: cache-volume
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
        - name: scheduler
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: FOSSOLOGY_DB_HOST
              value: {{ include "fossology.fullname" . }}-db
            - name: FOSSOLOGY_DB_NAME
              value: {{ .Values.fossology.db_name }}
            - name: FOSSOLOGY_DB_USER
              value: {{ .Values.fossology.db_user }}
            - name: FOSSOLOGY_DB_PASSWORD
              value: {{ .Values.fossology.db_passord }}
          ports:
            - name: scheduler
              containerPort: 80
              hostPort: 8080
              protocol: TCP
          command:
             - "/fossology/docker-entrypoint.sh"
             - "scheduler"
          volumeMounts:
            - mountPath: /srv/fossology/repository/
              name: cache-volume
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: cache-volume
          emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
